/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSidebarTreeRouteImport } from './routes/api/sidebar-tree'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiPagesRouteImport } from './routes/api/pages'
import { Route as ApiOpenapiRouteImport } from './routes/api/openapi'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiUploadImageRouteImport } from './routes/api/upload/image'
import { Route as ApiPagesSlugRouteImport } from './routes/api/pages/$slug'
import { Route as ApiPagesSlugHistoryRouteImport } from './routes/api/pages/$slug/history'
import { Route as ApiPagesSlugActionsRouteImport } from './routes/api/pages/$slug/actions'
import { Route as ApiPagesSlugRevisionsRevisionIdRouteImport } from './routes/api/pages/$slug/revisions/$revisionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSidebarTreeRoute = ApiSidebarTreeRouteImport.update({
  id: '/api/sidebar-tree',
  path: '/api/sidebar-tree',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPagesRoute = ApiPagesRouteImport.update({
  id: '/api/pages',
  path: '/api/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiRoute = ApiOpenapiRouteImport.update({
  id: '/api/openapi',
  path: '/api/openapi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadImageRoute = ApiUploadImageRouteImport.update({
  id: '/api/upload/image',
  path: '/api/upload/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPagesSlugRoute = ApiPagesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiPagesRoute,
} as any)
const ApiPagesSlugHistoryRoute = ApiPagesSlugHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ApiPagesSlugRoute,
} as any)
const ApiPagesSlugActionsRoute = ApiPagesSlugActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => ApiPagesSlugRoute,
} as any)
const ApiPagesSlugRevisionsRevisionIdRoute =
  ApiPagesSlugRevisionsRevisionIdRouteImport.update({
    id: '/revisions/$revisionId',
    path: '/revisions/$revisionId',
    getParentRoute: () => ApiPagesSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/openapi': typeof ApiOpenapiRoute
  '/api/pages': typeof ApiPagesRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/api/sidebar-tree': typeof ApiSidebarTreeRoute
  '/api/pages/$slug': typeof ApiPagesSlugRouteWithChildren
  '/api/upload/image': typeof ApiUploadImageRoute
  '/api/pages/$slug/actions': typeof ApiPagesSlugActionsRoute
  '/api/pages/$slug/history': typeof ApiPagesSlugHistoryRoute
  '/api/pages/$slug/revisions/$revisionId': typeof ApiPagesSlugRevisionsRevisionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/openapi': typeof ApiOpenapiRoute
  '/api/pages': typeof ApiPagesRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/api/sidebar-tree': typeof ApiSidebarTreeRoute
  '/api/pages/$slug': typeof ApiPagesSlugRouteWithChildren
  '/api/upload/image': typeof ApiUploadImageRoute
  '/api/pages/$slug/actions': typeof ApiPagesSlugActionsRoute
  '/api/pages/$slug/history': typeof ApiPagesSlugHistoryRoute
  '/api/pages/$slug/revisions/$revisionId': typeof ApiPagesSlugRevisionsRevisionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/openapi': typeof ApiOpenapiRoute
  '/api/pages': typeof ApiPagesRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/api/sidebar-tree': typeof ApiSidebarTreeRoute
  '/api/pages/$slug': typeof ApiPagesSlugRouteWithChildren
  '/api/upload/image': typeof ApiUploadImageRoute
  '/api/pages/$slug/actions': typeof ApiPagesSlugActionsRoute
  '/api/pages/$slug/history': typeof ApiPagesSlugHistoryRoute
  '/api/pages/$slug/revisions/$revisionId': typeof ApiPagesSlugRevisionsRevisionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/health'
    | '/api/openapi'
    | '/api/pages'
    | '/api/search'
    | '/api/sidebar-tree'
    | '/api/pages/$slug'
    | '/api/upload/image'
    | '/api/pages/$slug/actions'
    | '/api/pages/$slug/history'
    | '/api/pages/$slug/revisions/$revisionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/health'
    | '/api/openapi'
    | '/api/pages'
    | '/api/search'
    | '/api/sidebar-tree'
    | '/api/pages/$slug'
    | '/api/upload/image'
    | '/api/pages/$slug/actions'
    | '/api/pages/$slug/history'
    | '/api/pages/$slug/revisions/$revisionId'
  id:
    | '__root__'
    | '/'
    | '/api/health'
    | '/api/openapi'
    | '/api/pages'
    | '/api/search'
    | '/api/sidebar-tree'
    | '/api/pages/$slug'
    | '/api/upload/image'
    | '/api/pages/$slug/actions'
    | '/api/pages/$slug/history'
    | '/api/pages/$slug/revisions/$revisionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiOpenapiRoute: typeof ApiOpenapiRoute
  ApiPagesRoute: typeof ApiPagesRouteWithChildren
  ApiSearchRoute: typeof ApiSearchRoute
  ApiSidebarTreeRoute: typeof ApiSidebarTreeRoute
  ApiUploadImageRoute: typeof ApiUploadImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sidebar-tree': {
      id: '/api/sidebar-tree'
      path: '/api/sidebar-tree'
      fullPath: '/api/sidebar-tree'
      preLoaderRoute: typeof ApiSidebarTreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pages': {
      id: '/api/pages'
      path: '/api/pages'
      fullPath: '/api/pages'
      preLoaderRoute: typeof ApiPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi': {
      id: '/api/openapi'
      path: '/api/openapi'
      fullPath: '/api/openapi'
      preLoaderRoute: typeof ApiOpenapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/image': {
      id: '/api/upload/image'
      path: '/api/upload/image'
      fullPath: '/api/upload/image'
      preLoaderRoute: typeof ApiUploadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pages/$slug': {
      id: '/api/pages/$slug'
      path: '/$slug'
      fullPath: '/api/pages/$slug'
      preLoaderRoute: typeof ApiPagesSlugRouteImport
      parentRoute: typeof ApiPagesRoute
    }
    '/api/pages/$slug/history': {
      id: '/api/pages/$slug/history'
      path: '/history'
      fullPath: '/api/pages/$slug/history'
      preLoaderRoute: typeof ApiPagesSlugHistoryRouteImport
      parentRoute: typeof ApiPagesSlugRoute
    }
    '/api/pages/$slug/actions': {
      id: '/api/pages/$slug/actions'
      path: '/actions'
      fullPath: '/api/pages/$slug/actions'
      preLoaderRoute: typeof ApiPagesSlugActionsRouteImport
      parentRoute: typeof ApiPagesSlugRoute
    }
    '/api/pages/$slug/revisions/$revisionId': {
      id: '/api/pages/$slug/revisions/$revisionId'
      path: '/revisions/$revisionId'
      fullPath: '/api/pages/$slug/revisions/$revisionId'
      preLoaderRoute: typeof ApiPagesSlugRevisionsRevisionIdRouteImport
      parentRoute: typeof ApiPagesSlugRoute
    }
  }
}

interface ApiPagesSlugRouteChildren {
  ApiPagesSlugActionsRoute: typeof ApiPagesSlugActionsRoute
  ApiPagesSlugHistoryRoute: typeof ApiPagesSlugHistoryRoute
  ApiPagesSlugRevisionsRevisionIdRoute: typeof ApiPagesSlugRevisionsRevisionIdRoute
}

const ApiPagesSlugRouteChildren: ApiPagesSlugRouteChildren = {
  ApiPagesSlugActionsRoute: ApiPagesSlugActionsRoute,
  ApiPagesSlugHistoryRoute: ApiPagesSlugHistoryRoute,
  ApiPagesSlugRevisionsRevisionIdRoute: ApiPagesSlugRevisionsRevisionIdRoute,
}

const ApiPagesSlugRouteWithChildren = ApiPagesSlugRoute._addFileChildren(
  ApiPagesSlugRouteChildren,
)

interface ApiPagesRouteChildren {
  ApiPagesSlugRoute: typeof ApiPagesSlugRouteWithChildren
}

const ApiPagesRouteChildren: ApiPagesRouteChildren = {
  ApiPagesSlugRoute: ApiPagesSlugRouteWithChildren,
}

const ApiPagesRouteWithChildren = ApiPagesRoute._addFileChildren(
  ApiPagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiOpenapiRoute: ApiOpenapiRoute,
  ApiPagesRoute: ApiPagesRouteWithChildren,
  ApiSearchRoute: ApiSearchRoute,
  ApiSidebarTreeRoute: ApiSidebarTreeRoute,
  ApiUploadImageRoute: ApiUploadImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
